config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create, :destroy]
    end
  end

  root 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, class_name: 'Post', foreign_key: :post_id
  belongs_to :user, class_name: 'User', foreign_key: :user_id

  after_save :update_comment_counter

  def update_comment_counter
    post.update(commentsCounter: post.comments.count)
  end

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :post, class_name: 'Post', foreign_key: :post_id

  after_save :update_like_counter
  after_destroy :update_like_counter

  def update_like_counter
    post.update(likesCounter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_post_counter

  def update_post_counter
    user.update(postsCounter: user.posts.count)
  end

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  validates :title, presence: true, length: { maximum: 255,
                                              too_long: '255 characters is the maximum allowed' }
  validates :commentsCounter, numericality: { only_integer: true,
                                              greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { only_integer: true,
                                           greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end

  def update_avatar
    if avatar.attached?
      avatar
    else
      'default_avatar.png'
    end
  end

  validates :name, presence: true, length: { in: 2..100, message: 'Should be in range of 2 to 100' }

  private
  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app', 'assets', 'images', 'default_avatar.png'
          ),
          filename: 'default_avatar.png',
          content_type: 'image/png'
        )
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  # before_action :current_user
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :photo, :bio, :password, :password_confirmation, :avatar)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :photo, :bio, :password, :current_password, :avatar)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = @user.comments.create(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post = @post
    puts 'tototo'
    if @comment.save
      redirect_to user_post_path(@user.id, @post.id), notice: 'comment added successfully'
    else
      redirect_to user_post_path(@user.id, @post.id), alert: 'Comment failed to save.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.includes(:user).find(params[:post_id])

    @already_liked = Like.where(user: @user, post: @post)
    destroy && return if @already_liked.present?

    @like = Like.create(likes_params)
    @like.user = @user
    @like.post = @post

    if @like.save
      redirect_back_or_to user_post_path(@post.user, @post), notice: 'Successfully liked post.'
    else
      flash[:alert] = 'Something went wrong'
    end
  end

  def destroy
    @like = @user.likes.last
    @like.destroy
    @post = @like.post
    flash[:notice] = 'You unliked this post.'
    redirect_back_or_to user_post_path(@post.user, @post)
  end

  private

  def likes_params
    params.permit(:author_id, :id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, only: %w[index new create]

  def index
    @posts = Post.where(user: @user).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.where(post: @post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = @user.posts.create(post_params)
    @post.likesCounter = 0
    @post.commentsCounter = 0

    if @post.save
      redirect_to user_posts_path(@post.user, @post), notice: 'New post created successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(postsCounter: :desc)
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user: @user).order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def can_be_show?(item)
    item.nil? || item.count.zero?
  end
end

app/views/comments/new.html.erb
<%= render partial: "/posts/message"%>
<div class="container">
    <h1>Add new comment</h1>
    <%= bootstrap_form_with model: @comment, url: user_post_comments_path(user_id: @user.id, post_id: @post.id) do |f| %>
        <%= f.text_area :text, placeholder: 'Your comment here' %><br>
        <%= f.submit "Submit", class: "btn btn-secondary" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%
=begin%>
 <%= javascript_importmap_tags %> 
<%
=end%>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <% if user_signed_in? %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, data: { turbo: false }, class:"btn btn-danger" %>
    <% end %>
  </body>
</html>

app/views/posts/_message.html.erb
<% if flash[:notice]%>
  <div class="alert alert-info mt-4" role="alert">
    <%=  flash[:notice] %>
  </div>
<%end%>
<% if flash[:alert]%>
  <div class="alert alert-warning mt-4" role="alert">
    <%=  flash[:alert] %>
  </div>
<%end%>

app/views/posts/index.html.erb
<% render partial: "message" %>
<div class="container">
   <h1>Show posts</h1>
   <div class="row">
      <div class="col-sm-2">
         <img src=<%= @user.photo %>>
      </div>
      <div class="col-sm-5">
         <h3><%= @user.name %></h3>
         <blockquote class="text-end">Number of post: <%= @user.postsCounter %></blockquote>
      </div>
      <div class="row my-3">
         <p><%= @user.bio %></p>
         <%= link_to "Add a post", new_user_post_path(@user), class: "btn btn-dark w-50 m-auto" %>
      </div>
   </div>
      <span>
      <% counter = 0%>
      <% @posts.each do |item| %>
         <%= link_to user_post_path(@user, item) do %>
         <div class="w-50 row text-body border">
            <blockquote>Post #<%= counter += 1 %></blockquote>
            <p>lorem ipsum dolor sit amet, consectetur adipiscing elit. <%= item.text %></p>
            <blockquote class="text-end">Comments: <%= item.commentsCounter%> Likes: <%= item.likesCounter %></blockquote>
         </div>
         <% end %>
         <div class="row ms-4 border w-25">
            <% item.most_recent_comments.each do |comment| %>
               <p><mark><%= comment.user.name %></mark>: <%= comment.text %></p>
            <% end %>
         </div>
      <%end%>
   </span>
   <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1> Add a new post <h2>
  <%= bootstrap_form_with(model: @post, url: user_posts_path(@user)) do |f| %>
    <%= f.text_field :title, class: "form-control", placeholder: 'title'%>
    <%= f.text_area :text, class: "form-control", placeholder: 'text' %>
    <%= f.submit "submit" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render partial: "message"%>
<div class="container">
  <h1>A single post</h1>
  <div class="w-50">
    <p>post #1 by <%= @post.user.name %></p>
    <p class="text"><%= @post.text %></p>
    <blockquote class="text-end">Comments: <%= @post.commentsCounter%> Likes: <%= @post.likesCounter %></blockquote>
    <p><%= link_to "Comment", new_user_post_comment_path(user_id: @post.user_id, post_id: @post.id), class: "btn btn-dark" %>
    <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |f| %>
      <%= f.submit "Like" %>
    <% end %></p>
  </div>
  <div>
      <% @comments.each do |comment| %>
          <p><%= comment.user.name + ': ' + comment.text %></p>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
   <h1>User pages </h1>
   <% @users.each do |item| %>
      <%= link_to user_path(item) do%>
         <div class="row m-2 border w-50">
            <div class="col-sm-2">
               <%= image_tag(item.avatar, size: "150x150", alt: "User avatar") if item.avatar.attached? %>
            </div>
            <div class="col-sm-5 text-body">
               <h3><%= item.name %></h3>
               <blockquote class="text-end">Number of post: <%= item.postsCounter %></blockquote>
            </div>
         </div>
      <% end %>
   <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>Show users </h1>
  <div class="row">
      <div class="col-sm-1"><%= image_tag(@user.avatar) if @user.avatar.attached? %></div>
      <div class="col-sm-5">
         <h3><%= @user.name %></h3>
         <blockquote class="text-end">Number of post: <%= @user.postsCounter %></blockquote>
      </div>
   </div>
   <div class="row mb-5">
      <p><%= @user.bio %></p>
   </div>
   <% counter = 0%>
   <% @posts.each do |item|%>
      <div class="row mb-2 w-50 border" width="400px">
         <blockquote class="text-start">Post #<%= counter += 1 %></blockquote>
         <p>lorem ipsum dolor sit amet, consectetur adipiscing elit. <%= item.text %></p>
         <blockquote class="text-end">Comments: <%= item.commentsCounter%> Likes: <%= item.likesCounter %></blockquote>
      </div>
   <%end%>
 <%= link_to 'See all posts', user_posts_path(@user), class: "btn btn-dark"  unless can_be_show?(@posts) %>
</div> 